---
spring:
  config:
    activate:
      on-profile: db-local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/PARTNER3P
    username: root
    password: root
    hikari:
      maximumPoolSize: 5
      minimumIdle: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 200
        query:
          in_clause_parameter_padding: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
